import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const inputPath = require.resolve('../sql/gc_empty.sql');
const outputUrl = new URL('../src/sql/gc_empty.ts', import.meta.url);

const sql = await readFile(inputPath, 'utf8');

const contents = `// This file is generated by scripts/codegen-sql.mjs. Do not edit.
const { freeze } = Object;

export const gcEmptySql = freeze(${JSON.stringify(sql)});
`;

await writeFile(outputUrl, contents);
console.log(`wrote ${outputUrl.pathname}`);
