rules:
  indent:
    - 2
    - 4
  quotes:
    - 1
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  no-console:
    - 1
  no-unused-vars:
    - 2
    - { args: all, argsIgnorePattern: "^_" }
  no-var:
    - 1
env:
  es6: true
  node: true
extends: 'eslint:recommended'
